import * as fs from "fs";
import * as os from "os";
import * as path from "path";

// Above this many chars, the extracted text would overflow the context window if injected
// whole (and get silently truncated downstream). Instead we save the FULL text to a file and
// inject a preview + a pointer. Override with REI_OCR_INLINE_MAX_CHARS. ~40k chars ≈ ~10k tok.
const DEFAULT_INLINE_MAX_CHARS = 40000;

function intEnv(name: string, fallback: number): number {
  const n = parseInt(process.env[name] ?? "", 10);
  return Number.isFinite(n) && n > 0 ? n : fallback;
}

export interface PreparedDoc {
  /** Text to inject into the prompt (full text, or a preview + pointer when too large). */
  inject: string;
  /** Where the full text was written, if it was saved. */
  savedPath?: string;
  /** True when the injected text is a preview (full text lives in the file). */
  truncated: boolean;
}

/**
 * Decides how to surface extracted document text. Large docs (84-page PDFs, etc.) can't fit a
 * local context window, so instead of dumping everything (which gets truncated silently) we
 * write the FULL text to `<source>.ocr.md` and inject a preview + a pointer to the file. Small
 * docs inject whole. `REI_OCR_SAVE=1` forces the file even for small docs.
 */
export async function prepareExtractedText(
  sourcePath: string,
  fullText: string,
  pages: number,
  opts?: { workspacePath?: string },
): Promise<PreparedDoc> {
  const inlineMax = intEnv("REI_OCR_INLINE_MAX_CHARS", DEFAULT_INLINE_MAX_CHARS);
  const forceSave = process.env.REI_OCR_SAVE === "1";
  const isLarge = fullText.length > inlineMax;

  const savedPath =
    forceSave || isLarge
      ? await writeOcrFile(sourcePath, fullText, pages, opts?.workspacePath)
      : undefined;

  if (isLarge) {
    const preview = fullText.slice(0, inlineMax);
    const pointer = savedPath
      ? `Full text saved to ${savedPath} — open it, grep it, or reference @${savedPath} to ` +
        `ask about a specific section (a large-window cloud model fits much more at once).`
      : `Ask about a specific section.`;
    const note =
      `\n\n[… TRUNCATED for context — this document is large (${pages} page(s), ` +
      `~${fullText.length} chars) and does not fit the window. ${pointer}]`;
    return { inject: preview + note, savedPath, truncated: true };
  }

  const note = savedPath ? `\n\n[Full text also saved to ${savedPath}.]` : "";
  return { inject: fullText + note, savedPath, truncated: false };
}

/**
 * Resolves the output directory for OCR text. Stays INSIDE the workspace — never writes next
 * to the source (which may live in ~/Downloads etc.), so the file is @-referenceable and REI
 * doesn't touch dirs outside the project. Default: `<workspace>/.rei/ocr` (gitignored, same
 * convention as sessions/logs). Override with REI_OCR_OUT_DIR (absolute, or relative to the
 * workspace). Falls back to the source dir only when the workspace is unknown.
 */
function resolveOutDir(sourcePath: string, workspacePath?: string): string {
  const configured = process.env.REI_OCR_OUT_DIR;
  if (configured) {
    return path.isAbsolute(configured)
      ? configured
      : path.resolve(workspacePath ?? process.cwd(), configured);
  }
  if (workspacePath) return path.join(workspacePath, ".rei", "ocr");
  return path.dirname(sourcePath);
}

/** Writes the full extracted text to `<workspace>/.rei/ocr/<base>.ocr.md` (tmp on failure). */
async function writeOcrFile(
  sourcePath: string,
  fullText: string,
  pages: number,
  workspacePath?: string,
): Promise<string | undefined> {
  const base = path.basename(sourcePath, path.extname(sourcePath));
  const header =
    `# Extracted text — ${path.basename(sourcePath)}\n\n` +
    `> ${pages} page(s), ${fullText.length} chars. Generated by REI OCR.\n\n---\n\n`;
  const body = header + fullText;

  const outDir = resolveOutDir(sourcePath, workspacePath);
  const primary = path.join(outDir, `${base}.ocr.md`);
  try {
    await fs.promises.mkdir(outDir, { recursive: true });
    await fs.promises.writeFile(primary, body, "utf-8");
    return primary;
  } catch {
    try {
      const fallback = path.join(os.tmpdir(), `${base}.ocr.md`);
      await fs.promises.writeFile(fallback, body, "utf-8");
      return fallback;
    } catch {
      return undefined;
    }
  }
}
