export const DECISION_RETRIES = 2;
export const PATCH_CRITIC_RETRIES = 2;
export const RETRYABLE_PATCH_CODES = new Set<string>([
  "GIT_APPLY_CHECK_FAILED",
  "INVALID_PATCH_HEADERS",
  "MISSING_HUNKS",
  "TARGET_FILE_MISMATCH",
  "AST_VALIDATION_FAILED",
]);
