import { describe, it, expect } from "vitest";
import { chunkDocument } from "./chunker.js";

describe("chunkDocument (page-aware)", () => {
  it("tags chunks with page numbers from pdf-parse markers", () => {
    const doc = "Page one content here.\n-- 1 of 2 --\nPage two content here.\n-- 2 of 2 --";
    const chunks = chunkDocument(doc);
    expect(chunks.map((c) => c.page)).toEqual([1, 2]);
    expect(chunks[0].text).toContain("Page one");
    expect(chunks[1].text).toContain("Page two");
  });

  it("tags chunks from scanned `--- Page N ---` markers", () => {
    const doc = "--- Page 1 ---\nAlpha.\n\n--- Page 2 ---\nBeta.";
    const chunks = chunkDocument(doc);
    expect(chunks.map((c) => c.page)).toEqual([1, 2]);
  });

  it("strips the generated OCR header", () => {
    const doc =
      "# Extracted text — x.pdf\n\n> 2 page(s), 10 chars. Generated by REI OCR.\n\n---\n\n" +
      "Real content.\n-- 1 of 1 --";
    const chunks = chunkDocument(doc);
    expect(chunks[0].text).not.toContain("Extracted text");
    expect(chunks[0].text).toContain("Real content");
    expect(chunks[0].page).toBe(1);
  });

  it("falls back to page 0 when there are no markers", () => {
    const chunks = chunkDocument("Just some text with no page markers at all.");
    expect(chunks).toHaveLength(1);
    expect(chunks[0].page).toBe(0);
  });
});
