import { describe, it, expect } from "vitest";
import { parsePageSpec, sliceDocument } from "./slice.js";

const DOC =
  "# Extracted text — x.pdf\n\n> 3 page(s), 10 chars. Generated by REI OCR.\n\n---\n\n" +
  "Opening paragraph of page one.\n-- 1 of 3 --\nMiddle content page two.\n-- 2 of 3 --\n" +
  "Final content page three.\n-- 3 of 3 --";

describe("parsePageSpec", () => {
  it("parses ranges, single pages and 'first N'", () => {
    expect(parsePageSpec("pp.20-40")).toEqual({ from: 20, to: 40 });
    expect(parsePageSpec("p.5")).toEqual({ from: 5 });
    expect(parsePageSpec("20-40")).toEqual({ from: 20, to: 40 });
    expect(parsePageSpec("first 2")).toEqual({ first: 2 });
    expect(parsePageSpec("primeras 3")).toEqual({ first: 3 });
    expect(parsePageSpec("second page")).toEqual({ from: 2 });
    expect(parsePageSpec("segunda página")).toEqual({ from: 2 });
    expect(parsePageSpec("first page")).toEqual({ from: 1 });
    expect(parsePageSpec("page 5")).toEqual({ from: 5 });
    expect(parsePageSpec("página 7")).toEqual({ from: 7 });
    expect(parsePageSpec("nonsense")).toBeUndefined();
  });
});

describe("sliceDocument", () => {
  it("defaults to the first page (strips the OCR header)", () => {
    const s = sliceDocument(DOC);
    expect(s.pages).toEqual([1]);
    expect(s.text).toContain("Opening paragraph of page one");
    expect(s.text).not.toContain("Extracted text");
    expect(s.text).not.toContain("Middle content");
  });

  it("slices a page range with headers", () => {
    const s = sliceDocument(DOC, { from: 2, to: 3 });
    expect(s.pages).toEqual([2, 3]);
    expect(s.text).toContain("--- Page 2 ---");
    expect(s.text).toContain("Middle content");
    expect(s.text).toContain("Final content");
    expect(s.text).not.toContain("Opening paragraph");
  });

  it("honors 'first N'", () => {
    expect(sliceDocument(DOC, { first: 2 }).pages).toEqual([1, 2]);
  });
});
